import { Inter } from "next/font/google";
import Header from "./components/Header";
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import ctheme from './components/theme'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-7CBMC00V5W"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-7CBMC00V5W');
            `,
          }}
        />
      </Head>
      <body className={inter.className}>
        <ThemeProvider theme={ctheme}>
          <CssBaseline /> 
          <Header/>
          <main>{children}</main> 
        </ThemeProvider>
        </body>
    </html>
  );
}
