import { Inter } from "next/font/google";
import Header from "./components/Header";
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import ctheme from './components/theme'
import Script from 'next/script';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <Script
        id='gtm'
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-P672TFL9');`
        }}
      >
        

      </Script>
            
      <body className={inter.className}>
        <ThemeProvider theme={ctheme}>
          <CssBaseline /> 
          <Header/>
          <main>{children}</main> 
        </ThemeProvider>
        </body>
    </html>
  );
}
